Adds parsing for objectives
Laboratoria/curriculum-parser pull request #86
Opened 2023-12-11 23:22 UTC by unjust

addresses #85 

Example output
```
The following 72 objectives are not found in intl files:
Missing objective: js/data-types for langs es, pt
Missing objective: js/testing for langs es, pt
Missing objective: js/modules for langs es, pt
Missing objective: js/async for langs es, pt
Missing objective: scm/git for langs es, pt
Missing objective: scm/github for langs es, pt
Missing objective: front-end-web-dev for langs es, pt
Missing objective: front-end-web-dev/components for langs es, pt
Missing objective: front-end-web-dev/state for langs es, pt
Missing objective: java/spring-framework/spring-web/request-param for langs es
Missing objective: php/data-types for langs es, pt
Missing objective: php/testing for langs es, pt
Missing objective: php/package-management for langs es, pt
Missing objective: wordpress/plugin-development for langs es, pt
Missing objective: typescript for langs es, pt
Missing objective: typescript/basic-types for langs es, pt
Missing objective: agile-planning for langs es, pt
Missing objective: agile-planning/scope for langs pt
Missing objective: agile-planning/workplan for langs pt
Missing objective: agile-planning/tasks for langs pt
Missing objective: business-understanding for langs es, pt
Missing objective: business-understanding/business-model for langs pt
Missing objective: business-understanding/goals-and-kpis for langs pt
Missing objective: business-understanding/benchmark for langs pt
Missing objective: research/planning/research-plan for langs pt
Missing objective: research/planning/desk-research for langs pt
Missing objective: research/planning/research-sample for langs pt
Missing objective: research/planning/participants for langs pt
Missing objective: research/qualitative for langs es, pt
Missing objective: research/qualitative/user-interviews for langs pt
Missing objective: research/qualitative/exploratory-techniques for langs pt
Missing objective: research/quantitative for langs es, pt
Missing objective: research/quantitative/user-surveys for langs pt
Missing objective: research/quantitative/analytical-techniques for langs pt
Missing objective: research/analysis for langs es, pt
Missing objective: research/analysis/process-information for langs pt
Missing objective: research/analysis/experience-mapping for langs pt
Missing objective: research/analysis/identify-patterns for langs pt
Missing objective: research/analysis/synthesize-results for langs pt
Missing objective: design-concept for langs es, pt
Missing objective: design-concept/define-mvp for langs pt
Missing objective: design-concept/design-references for langs pt
Missing objective: design-concept/ideate for langs pt
Missing objective: design-concept/prioritize-ideas for langs pt
Missing objective: interaction-design for langs es, pt
Missing objective: interaction-design/user-flows for langs pt
Missing objective: interaction-design/usability for langs pt
Missing objective: interaction-design/information-architecture for langs pt
Missing objective: content-design for langs es, pt
Missing objective: content-design/voice-tone for langs pt
Missing objective: content-design/create-content for langs pt
Missing objective: interface-design for langs es, pt
Missing objective: interface-design/visual-design for langs pt
Missing objective: interface-design/accesibility for langs pt
Missing objective: interface-design/responsive-design for langs pt
Missing objective: design-prototype for langs es, pt
Missing objective: design-prototype/basic-prototypes for langs pt
Missing objective: design-prototype/high-fidelity for langs pt
Missing objective: design-prototype/advanced-interactions for langs pt
Missing objective: usability-analysis for langs es, pt
Missing objective: usability-analysis/moderated-testing for langs pt
Missing objective: usability-analysis/heuristic-analysis for langs pt
Missing objective: usability-analysis/non-moderated-testing for langs pt
Missing objective: design-pitch for langs es, pt
Missing objective: design-pitch/design-feedback for langs pt
Missing objective: design-pitch/design-presentation for langs pt
Missing objective: design-specs/file-organization for langs pt
Missing objective: design-specs/use-cases for langs pt
Missing objective: design-specs/project-documentation for langs pt
Missing objective: design-systems for langs es, pt
Missing objective: design-systems/atomic-design for langs pt
Missing objective: design-systems/design-system for langs pt
The following 1 objectives are missing titles in intl files:
Missing title for objective: design-specs for langs es, pt
```

2023-12-12 14:54 UTC, unjust commented on index.js
> +  .option('--debug', 'Show error stack traces')
aqui estoy pensando en agregar un option `--strict-locales` o algo asi para solo bota errores si no hay un OA en ningun intl/localized archivo. Podemos usar eso en `create-cohort-project` para no botar errores si solo tiene un OA de UX en español.

2023-12-13 13:49 UTC, mfdebian requested changes
¡Muchas gracias por el PR @unjust ! :blush: 

Creo que el cambio que pediría, a grandes rasgos es el de seguir la misma "API" que siguen los demás comandos, como el de `project` o `topic`, en el sentido de que ambas funciones, `parseProject` y `parseTopic` están siendo envueltas por la función `createHandler`, y es esa función la que invocará a las demás y evaluará la calidad de satisfecha o rechazada de las funciones e imprimirá su valor de retorno en caso de que haya `result`, o invocará la función `printError` en caso de que se devuelva un error. Entonces el comando de `objectives` debería retornar ese "error" y yo movería la lógica de los `console.warning` que quieres agregar a esa función `printError`, de esa manera se sigue el "flujo" que ocupan los demás comandos también (e imprime también la ruta de dónde se gatilla el error), y así también se puede generar en la función `parseLearningObjectives` un objeto de retorno donde se utilice la variable `opts` donde normalmente vendrían cosas como la versión, por ejemplo, ya que ahora la variable `opts` no se está utilizando en la función (y por eso explotan los checks actualmente). Dime qué opinas! si te hace sentido o no, creo que a grandes rasgos el feedback es sólo intentar que la API del comando `objectives` se parezca más a la de los demás comandos :blush: :metal:

2024-01-02 20:18 UTC, unjust commented
@mfdebian Por ahora la validacion es solo una herramienta que podemos usar corriendo curriculum parser de linea de comando.

Tengo que hacer otro cambio en curriculum repo si queremos que el build de curriculum toma esta output para generar sus jsons en dist.

2024-01-04 20:27 UTC, mfdebian reviewed
Al ejecutar tanto el comando

 `curriculum-parser objectives ../curriculum/learning-objectives/  --strict false` 
 
Como
 
 `curriculum-parser objectives ../curriculum/learning-objectives/  --strict true`
 
 Recibí el mismo resultado, supongo que no era eso lo esperado; Lo recibido, creo, es lo mismo que hay en https://curriculum.laboratoria.la/data/learning-objectives.json, me imagino que no era el output esperado, pero quizás yo entendí mal, pero me parece que la intención del PR es recibir un warning (o error con `strict = true`?) de cuáles son los `learning-objectives` que no tienen un título en algún (o ambos) idioma(s), no sé si es esa la intención o no, me avisas si falta algo! :raised_hands: 
 
 Por lo demás, te agradecería mucho si es que puedes agregarle tests a las funciones que agregarías :pray: eso ayudaría mucho a testear fácil el output esperado para cualquier caso! :blush:

2024-01-04 20:27 UTC, mfdebian commented on README.md
¡Gracias @unjust :blush: !

Aprovechando que estás cambiando el README para actualizar el nombre del repo de `Laboratoria/bootcamp` a `Laboratoria/curriculum` , faltó [en una parte](https://github.com/Laboratoria/curriculum-parser/pull/86/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R130-R136)

2024-01-04 20:27 UTC, mfdebian commented on README.md
> +  objectives [options] <dir> Parse objectives
Probablemente para todxs nosotrxs queda claro que `objectives` se refiere a los `learning-objectives`, pero sólo para que haya consistencia entre los nombres en los distintos repos, será que lo cambiamos a `learning-objectives`? o le estoy dando mucho color? :rofl:

2024-01-04 20:27 UTC, mfdebian commented on README.md
> +  --repo <string>     Repository
al incluir la opción de `repo` me arrojaba el error:

`error: unknown option '--repo'`

hoy en día no hace nada mucho esa opción, más que ser agregada al output final, pero de todas formas si la queremos agregar, debe agregarse como `option()` en el `index.js` para el comando de `objectives`

2024-01-04 20:27 UTC, mfdebian commented on README.md
> +```
Yo le agregaría a la sección de ejemplo una instrucción para arrojar el output hacia un archivo, que _creo_ sería el modo de uso más común

```suggestion
```sh
curriculum-parser objectives learning-objectives \
  --repo Laboratoria/curriculum \
  --strict false \
  > "dist/learning-objectives.json"
```
```

2024-01-05 17:15 UTC, unjust commented on README.md
> +  --repo <string>     Repository
Ok - pregunta, necesito incluir este opcion? Que opinas?

2024-01-08 17:06 UTC, unjust commented
> Al ejecutar tanto el comando
> 
> `curriculum-parser objectives ../curriculum/learning-objectives/ --strict false`
> 
> Como
> 
> `curriculum-parser objectives ../curriculum/learning-objectives/ --strict true`
> 
> Recibí el mismo resultado, supongo que no era eso lo esperado; Lo recibido, creo, es lo mismo que hay en 

Cambie el README y espero que es mas clara que `--strict` es solo un bandeja para usar con `--validate` si quiere `strict` ser "falso" solo no coloca el opcion.

> `curriculum-parser objectives ../curriculum/learning-objectives/ --strict --validate`
> `curriculum-parser objectives ../curriculum/learning-objectives/ --validate`

2024-01-08 17:07 UTC, unjust commented on README.md
> +  --repo <string>     Repository
Lo quite

2024-01-08 21:00 UTC, mfdebian reviewed
Mil gracias @unjust por los cambios, creo que aún faltaría actualizar el README para que incluya correctamente los ejemplos, pero sólo para entenderlo bien bien, lo que propones tiene 3 líneas de ejecución por así decirlo, una que es de la forma:

`curriculum-parser learning-objectives ../curriculum/learning-objectives/` y que retorna un JSON que incluye sus objetos `tree`, `flat`, `table`, etc... que podríamos utilizar en el repo de `curriculum` para generar el archivo [`learning-objectives.json`](https://curriculum.laboratoria.la/data/learning-objectives.json) no?

Luego está la opción con `validate`:

`curriculum-parser learning-objectives ../curriculum/learning-objectives/ --validate`

Que en mi caso retorna lo siguiente:

```sh
Learning objectives missing from intl:
js/data-types missing in langs: es,pt
js/testing missing in langs: es,pt
js/modules missing in langs: es,pt
js/async missing in langs: es,pt
scm/git missing in langs: es,pt
scm/github missing in langs: es,pt
front-end-web-dev missing in langs: es,pt
front-end-web-dev/components missing in langs: es,pt
front-end-web-dev/state missing in langs: es,pt
java/spring-framework/spring-web/request-param missing in langs: es
php/data-types missing in langs: es,pt
php/testing missing in langs: es,pt
php/package-management missing in langs: es,pt
wordpress/plugin-development missing in langs: es,pt
typescript missing in langs: es,pt
typescript/basic-types missing in langs: es,pt
agile-planning missing in langs: es,pt
agile-planning/scope missing in langs: pt
agile-planning/workplan missing in langs: pt
agile-planning/tasks missing in langs: pt
business-understanding missing in langs: es,pt
business-understanding/business-model missing in langs: pt
business-understanding/goals-and-kpis missing in langs: pt
business-understanding/benchmark missing in langs: pt
research/planning/research-plan missing in langs: pt
research/planning/desk-research missing in langs: pt
research/planning/research-sample missing in langs: pt
research/planning/participants missing in langs: pt
research/qualitative missing in langs: es,pt
research/qualitative/user-interviews missing in langs: pt
research/qualitative/exploratory-techniques missing in langs: pt
research/quantitative missing in langs: es,pt
research/quantitative/user-surveys missing in langs: pt
research/quantitative/analytical-techniques missing in langs: pt
research/analysis missing in langs: es,pt
research/analysis/process-information missing in langs: pt
research/analysis/experience-mapping missing in langs: pt
research/analysis/identify-patterns missing in langs: pt
research/analysis/synthesize-results missing in langs: pt
design-concept missing in langs: es,pt
design-concept/define-mvp missing in langs: pt
design-concept/design-references missing in langs: pt
design-concept/ideate missing in langs: pt
design-concept/prioritize-ideas missing in langs: pt
interaction-design missing in langs: es,pt
interaction-design/user-flows missing in langs: pt
interaction-design/usability missing in langs: pt
interaction-design/information-architecture missing in langs: pt
content-design missing in langs: es,pt
content-design/voice-tone missing in langs: pt
content-design/create-content missing in langs: pt
interface-design missing in langs: es,pt
interface-design/visual-design missing in langs: pt
interface-design/accesibility missing in langs: pt
interface-design/responsive-design missing in langs: pt
design-prototype missing in langs: es,pt
design-prototype/basic-prototypes missing in langs: pt
design-prototype/high-fidelity missing in langs: pt
design-prototype/advanced-interactions missing in langs: pt
usability-analysis missing in langs: es,pt
usability-analysis/moderated-testing missing in langs: pt
usability-analysis/heuristic-analysis missing in langs: pt
usability-analysis/non-moderated-testing missing in langs: pt
design-pitch missing in langs: es,pt
design-pitch/design-feedback missing in langs: pt
design-pitch/design-presentation missing in langs: pt
design-specs missing in langs: es,pt
design-specs/file-organization missing in langs: pt
design-specs/use-cases missing in langs: pt
design-specs/project-documentation missing in langs: pt
design-systems missing in langs: es,pt
design-systems/atomic-design missing in langs: pt
design-systems/design-system missing in langs: pt
==> 73 objectives missing from intl
----
└── ../curriculum/learning-objectives/
```

Y en ese caso **no** retorna un JSON.

y la 3era opción que sería con `validate` y `strict`:

`curriculum-parser learning-objectives ../curriculum/learning-objectives/ --validate --strict`

Que en mi caso retorna:

```sh
Learning objectives missing from intl:
js/data-types missing in langs: es,pt
js/testing missing in langs: es,pt
js/modules missing in langs: es,pt
js/async missing in langs: es,pt
scm/git missing in langs: es,pt
scm/github missing in langs: es,pt
front-end-web-dev missing in langs: es,pt
front-end-web-dev/components missing in langs: es,pt
front-end-web-dev/state missing in langs: es,pt
php/data-types missing in langs: es,pt
php/testing missing in langs: es,pt
php/package-management missing in langs: es,pt
wordpress/plugin-development missing in langs: es,pt
typescript missing in langs: es,pt
typescript/basic-types missing in langs: es,pt
agile-planning missing in langs: es,pt
business-understanding missing in langs: es,pt
research/qualitative missing in langs: es,pt
research/quantitative missing in langs: es,pt
research/analysis missing in langs: es,pt
design-concept missing in langs: es,pt
interaction-design missing in langs: es,pt
content-design missing in langs: es,pt
interface-design missing in langs: es,pt
design-prototype missing in langs: es,pt
usability-analysis missing in langs: es,pt
design-pitch missing in langs: es,pt
design-specs missing in langs: es,pt
design-systems missing in langs: es,pt
==> 29 objectives missing from intl
----
└── ../curriculum/learning-objectives/
```

Y tampoco retorna un JSON.

Creo que lo que no me queda claro aún (disculpa :see_no_evil: ) es cuál es la diferencia entre `--validate` y `--validate --strict`, ambos parecieran _haltear_ la ejecución del programa y no retornar ningún JSON al final, pero sobretodo, el README no explica aún el caso de uso que los diferencia, aún no entiendo bien la diferencia entre ambos :see_no_evil: si quieres mañana lo conversamos un poco más y vemos cómo podemos agregar esa documentación al README

Por lo demás, muchas gracias por tomarte el tiempo @unjust y disculpa que me cueste tanto entenderlo bien :rofl:

2024-01-08 21:00 UTC, mfdebian commented on README.md
> +  learning-objectives [options] <dir> Parse objectives
```suggestion
  project [options] <dir>             Parse a project
  topic [options] <dir>               Parse a topic
  part [options] <dir>                Parse a part
  challenge [options] <dir>           Parse a challenge
  learning-objectives [options] <dir> Parse learning objectives
  help [command]                      Display help for command
```

Le agregaría el espaciado para que quede fácil de leer (el review de Github no me dejó agregarle la línea 97, de `project`, habría que agregarla a este cambio)

2024-01-08 21:00 UTC, mfdebian commented on README.md
> +### Parse a topic within the `Laboratoria/curriculum` repo
gracias! :pray:

2024-01-08 21:00 UTC, mfdebian commented on README.md
> +  > "dist/learning-objectives.json"
Al final esto ya no sería así no? es decir, el comando sería

`curriculum-parser learning-objectives learning-objectives/ --validate` sin `strict`, y `curriculum-parser learning-objectives learning-objectives/ --validate --strict` con el `strict`, cierto? :grin: 

no incluiría la opciones de `repo`, y creo que está también la 3era opción, que es la sin `validate` ni `strict`, que es la única que retornaría un output en formato `json`, si lo entendí bien, es así? :blush:

2024-01-15 16:12 UTC, unjust commented
@mfdebian me avisas si has probado. Creo la duda que queda (aparte si el codigo es hecho bien) es si seria util incluir los opciones de `repo` (no creo) y `version` (quizas).

2024-02-29 18:48 UTC, mfdebian requested changes
Hola @unjust! volví a ejecutar el comando en mi local, veo que la función para devolver ese JSON con las propiedades `tree`, `flat`, `intl` y `table` funciona bien, pero a mi aún no me queda claro el resto de la funcionalidad del programa, al ejecutar el comando:
`curriculum-parser learning-objectives ../curriculum/learning-objectives/ --validate`
El programa se bota y no sigue ejecutándose, incluso al revisar el [_exit status_](https://www.redhat.com/sysadmin/exit-codes-demystified) del programa, me sale con código 1, es decir, ocurrió un error en la ejecución del programa, ¿es ese el comportamiento esperado? ¿qué pasa en el caso de que no arroje errores? qué debería retornar? :grin: 

porfa ayúdame a entender bien esas últimas 2 preguntas y ya lo aprobamos nomas, el código me parece ok! :blush: :raised_hands:

2024-02-29 18:48 UTC, mfdebian commented on README.md
> +curriculum-parser objectives learning-objectives \
```suggestion
curriculum-parser learning-objectives learning-objectives \
```

2024-02-29 18:48 UTC, mfdebian commented on lib/learning-objectives.js
> +// import { detectLangs } from './common.js';
```suggestion

```

2024-03-21 17:09 UTC, unjust commented
@mfdebian muy agredecida de este feedback. No me di cuenta que aun habia errores cuando no deberia ser.
Vas a ver ahora que cuando corre el script sin `--validate` siempre debe tener un `exit status 0`
Y cuando corre con validate y no hay errores tambien debe tener un `exit status 0`

Con `--validate` si hay objetivos invalidos, van a tirar errores y salir con `status 1`

Agregue algunos tests de cubrir los casos.

2024-04-03 23:35 UTC, unjust commented on README.md
> +  -h, --help          display help for command
quiero validar si `--debug` y `--help` funciona

y aun no se si debe aceptar `repo` y `version` si sean utiles para tener?
repo y version son argumentos de project pero tampoco se si estes argumentos aprecen en el json resultado.

2024-04-04 00:07 UTC, unjust commented
Compare el json actual de OAs con el output de parser y [parece igual con este diff](https://www.diffchecker.com/qfMiXuRU/)
Entonces si queremos [usar el parser para generar los objetivos con el build script](https://github.com/Laboratoria/curriculum/pull/1681/), creo podemos reemplazarlo normal

2024-04-05 14:01 UTC, mfdebian submitted a review, later dismissed
Unos últimos pequeños cambios para que quede okey y listo para mergear :see_no_evil: gracias @unjust !!! :raised_hands:

2024-04-05 14:01 UTC, mfdebian commented on lib/learning-objectives.js
> +  // const langs = await detectLangs(dir);
```suggestion
```

2024-04-08 16:09 UTC, unjust commented on README.md
> +  -h, --help          display help for command
Voy a agregar un issue para agregarlos aparte.
Cuando empezamos usar el output de objectives de curriculum parser en la curriculum build - seria bueno notar cual features usa el json objectives de curriculum (por ahora solo pienso de project feedback) para saber si aggregando estes propiedades van a tener algun impacto.

2024-04-08 16:10 UTC, unjust commented on lib/learning-objectives.js
> +  // Note: tried to use detectLangs but it only works with readmes :\
Creo voy a capturar eso en un issue tambien

2024-04-08 16:10 UTC, unjust commented on lib/learning-objectives.js
> +  }, { missingIntl: {}, noTitle: {} });
Gracias!

2024-04-08 16:11 UTC, unjust commented on lib/learning-objectives.js
> +// import { detectLangs } from './common.js';
ok! voy a adejar un issue que habla de detectLangs

2024-04-08 17:44 UTC, unjust commented on README.md
> +  -h, --help          display help for command
Issue #89

2024-04-08 18:48 UTC, unjust commented on README.md
> +  -h, --help          display help for command
Tambien valide que `help` y `debug` funciona

2024-09-09 15:29 UTC, fakel approved these changes
Todo parece estar ok, traté de ponerme al día con la conversación y parece que no hay problemas, si necesitas apoyo con el release me comentas, veo que no es algo que rompa la compatibilidad previa asi que no debería haber inconvenientes

2024-09-27 16:56 UTC, merged